### ISSUE TITLE
Is it possible to specify the boot order for NIC?

### ISSUE THREAD

**Issue by jlory** [fog/fog-libvirt#10]
I looked at the source code but it seems that it's not possible to specify the boot order for PXE when you have multiple NICs?

See the libvirt doc:

https://libvirt.org/formatdomain.html#elementsNICSBoot

**Comment by plribeiro3000** [comment]
@strzibny Any ideas on this?

**Comment by strzibny** [comment]
Right now I have no clue, I would have to take a closer look.

**Comment by mmoll** [comment]
what's the status here?

**Comment by jlory** [comment]
I don't use Foreman / fog-libvirt anymore, so I didn't do a follow-up on that issue.
