### ISSUE TITLE
Disable stale bot?

### ISSUE THREAD

**Issue by ekohl** [fog/fog-libvirt#108]
I think this does more harm than good. I felt this way for a long time but https://drewdevault.com/2021/10/26/stalebot.html inspired me to open an issue.

**Comment by lzap** [comment]
I have no objection, this is on @fog/fog-libvirt owners tho.

**Comment by strzibny** [comment]
I am not against keeping issues opened. Not sure how to change the settings for it.

**Comment by geemus** [comment]
I can certainly change it if you all want. In my experience most issues that are not addressed or commented on after 60 days simply don't get addressed or commented on, so it doesn't seem harmful to me to close them as being something the community is not currently interested in engaging with. Particularly as closed issues can still be searched for and/or re-opened if that changes. You can also add the `pinned` tag if particular issues are an exception to this. 

I don't have particularly strong feelings here though, so am happy to go with your preferences.
