### ISSUE TITLE
list_domains:domains_volumes only parses <source file=...>

### ISSUE THREAD

**Issue by idl0r** [fog/fog-libvirt#110]
Hi,

https://github.com/fog/fog-libvirt/blob/f2f75f0e493351a4cfecd269bbd3c4bb92a27fa6/lib/fog/libvirt/requests/compute/list_domains.rb#L42

that parses only definitions like:
```
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='none' io='native'/>
      <source file='/dev/mapper/s093043'/>
      <backingStore/>
      <target dev='vda' bus='virtio'/>
      <alias name='virtio-disk0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </disk>
```

However, there's also "dev" (type block) which seams to be valid as well?
```
    <disk type='block' device='disk'>
      <driver name='qemu' type='raw' cache='none' io='native'/>
      <source dev='/dev/mapper/s093250'/>
      <backingStore/>
      <target dev='vda' bus='virtio'/>
      <alias name='virtio-disk0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </disk>
```

The latter isn't covered by the above mentioned request.

volumes/volume_path would be nil then.

**Comment by idl0r** [comment]
Uhm, please disable that bot until someone looked at it?

**Comment by lestercheung** [comment]
Hi @ekohl 👋🏼
Now that this bug has been fixed - do you guys have a plan for a new release and bump the version used by Foreman?
Looking forward to hearing from you and your team.

**Comment by ekohl** [comment]
There's a 0.12.0 release out and it's in Foreman nightly now

**Comment by ekohl** [comment]
This should have been closed when #117 was merged.

**Comment by debdolph** [comment]
Foreman is still using 0.9.0 in develop :/ https://github.com/theforeman/foreman/blob/develop/bundler.d/libvirt.rb

**Comment by ekohl** [comment]
No, that's >= 0.9.0 so no upper bound
