### ISSUE TITLE
No ability to create libvirt KVM virtual machine instances with uefi support

### ISSUE THREAD

**Issue by rhjyoung** [fog/fog-libvirt#128]
Currently fog-libvirt only supports ability to create virtual machines via libvirt that are BIOS based. BIOS is slowly being deprecated on with Linux distributions. While Windows 11 no longer supports it all together.

Foreman currently relies on fog-libvirt to create virtual machines from a libvirt compute resource. Currently it can only support creation of BIOS based KVM virtual machines. 

Enabling a way to specify creation of libvirt KVM instances with UEFI will resolve this issue.

https://community.theforeman.org/t/libvirt-and-uefi/22756

**Comment by ekohl** [comment]
On a related note, https://github.com/fog/fog-libvirt/pull/132 would at least clean up the UEFI bits on deletion.

**Comment by ekohl** [comment]
https://libvirt.org/formatdomain.html#bios-bootloader describes how to do this. The simplest way to enable EFI is to select the right firmware
```xml
<os firmware="efi">
  # ...
</os>
```

Additionally, secure boot can be enabled with `<loader secure='yes'/>` and there's also stateless for AMD SEV `<loader stateless='yes'/>`. Stateless also means you can't store any configuration, but I don't know if that's needed. I saw very little configurable options when I played with it the last time.

Big question is, how to expose this. I suppose an attribute `os_firmware` is a good start. By default `nil`, but can be used to explicitly set either `bios` or `efi`. But then the loader. I'd like to avoid fully exposing all the options for now and simply say you can opt in for either secure or stateless (with qemu 8.6.0+).

**Comment by jeroney** [comment]
@ekol this seems about right. Now just needs to pass all the pipline checks. It wants double quotes instead of single quotes.

**Comment by rhjyoung** [comment]
Resolved with release version 0.13.0.
