### ISSUE TITLE
Nominating @nofaralfasi for commit access

### ISSUE THREAD

**Issue by ekohl** [fog/fog-libvirt#158]
Within the Foreman project we rely on fog-libvirt and currently I'm the only active committer on this project after @lzap moved on. I've been working with my colleague @nofaralfasi to address this.

@geemus I think you're the only one who can grant these permissions so can you take a look?

**Comment by geemus** [comment]
@ekohl Hey, sounds great. Thanks for continuing to work on it and finding others to help out.

@nofaralfasi You should get an invite to the org. Welcome and thanks for your help!

**Comment by ekohl** [comment]
@geemus not sure what your preference is here, but I noticed @nofaralfasi doesn't have permissions to publish the gem. I think I can give those permissions, but would like your opinion first.

**Comment by geemus** [comment]
Looks like this just went through. Thanks @ekohl and @nofaralfasi. Just let me know if you need anything else.

**Comment by ekohl** [comment]
Indeed. Thanks for keeping an eye on it. If we need anything, we'll let you know
