### ISSUE TITLE
Support for hostdev mode network

### ISSUE THREAD

**Issue by lemrouch** [fog/fog-libvirt#24]
Hi,
I have libvirt network with hostdev mode (pool of virtual NICs on PCI-E) and server is managed by Foreman.
This type of network seems to be unsupported by fog-libvirt.

&lt;network&gt;
  &lt;name&gt;pf-eth0&lt;/name&gt;
  &lt;uuid&gt;0ae0eb24-d0d9-4a02-942e-d245c77e12ba&lt;/uuid&gt;
  &lt;forward mode='hostdev' managed='yes'&gt;
    &lt;driver name='vfio'/&gt;
    &lt;pf dev='eth0'/&gt;
  &lt;/forward&gt;
&lt;/network&gt;

Backtace from foreman is attached as [trace.txt](https://github.com/fog/fog-libvirt/files/467088/trace.txt)

Is someone willing to add such support please?

**Comment by plribeiro3000** [comment]
Hello @lemrouch. I'm afraid we might be out of hands now.
Would you be able to submit a PR?

**Comment by ares** [comment]
Should be fixed by https://github.com/fog/fog-libvirt/pull/78

**Comment by plribeiro3000** [comment]
Cool. Thanks @ares
