### ISSUE TITLE
Port defaults to -1

### ISSUE THREAD

**Issue by td512** [fog/fog-libvirt#34]
Hey all,

In `libvirt/models/compute/templates/server.xml.erb` there is an error on line 49 that's causing the port to default to `-1`

Here's the fix:

`<% if display[:port] and !(display[:port].empty?) %>port='<%= display[:port] %>' autoport='no' <% else %>port='-1' autoport='yes' <%end%>` instead of `port='<%= display[:port] %>' autoport='yes'`

I've already tested it on my local cluster, and that stops the port defaulting to -1

**Comment by plribeiro3000** [comment]
@td512 Could you open a PR with those changes?

Thanks!

**Comment by td512** [comment]
All done @plribeiro3000

**Comment by plribeiro3000** [comment]
Awesome. Thanks @td512 . =)
