### ISSUE TITLE
Cloning volumes from templates when creating new VMs

### ISSUE THREAD

**Issue by td512** [fog/fog-libvirt#41]
Heyo,
I was wondering if there's a way to do this. I saw there's a `volume_template_name` attr, but when I try to use it, I get `Fog::Errors::Error (Error saving the server: Error creating the volume : identity is required for this operation)`

Cheers

**Comment by td512** [comment]
@plribeiro3000 would you know if there's a way to do this, and if my hunch is correct, why I'm getting that error?

**Comment by plribeiro3000** [comment]
It should work afaik.

Could you provide the stacktrace please?

**Comment by td512** [comment]
@plribeiro3000 that could be a slight issue. This is all I have
![screenshot](https://user-images.githubusercontent.com/9508934/27356573-12528500-5663-11e7-8e0d-30dad1ace958.png)
