### ISSUE TITLE
minitest/unit.rb:28:in `const_missing': uninitialized constant MiniTest::Test (NameError)

### ISSUE THREAD

**Issue by brianjmurrell** [fog/fog-libvirt#48]
Trying to build _fog-libvirt_ on CentOS 7, when I try to run the tests with:

```ruby -Iminitests -e "Dir.glob './minitests/**/*_test.rb', &method(:require)"```

I'm getting an error:

```
  Fog::Compute[:libvirt] | servers collection (libvirt)
    The servers collection
      + should not be empty
      + should be a kind of Fog::Compute::Libvirt::Servers
      should be able to reload itself + succeeds
      should be able to get a model
        by instance uuid + succeeds
  
  196 succeeded in 0.252094842 seconds
  
+ ruby -Iminitests -e 'Dir.glob '\''./minitests/**/*_test.rb'\'', &method(:require)'
/usr/share/gems/gems/minitest-4.3.2/lib/minitest/unit.rb:28:in `const_missing': uninitialized constant MiniTest::Test (NameError)
	from /builddir/build/BUILD/fog-libvirt-0.3.0/usr/share/gems/gems/fog-libvirt-0.3.0/minitests/server/user_data_iso_test.rb:3:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `glob'
	from -e:1:in `<main>'
```

Any idea what that might be caused by?

**Comment by plribeiro3000** [comment]
I'm not that much into minitest so i need a little extra information from you.

Does it work if you run the rake task?

**Comment by mmoll** [comment]
I guess minitest 5.x is needed.

**Comment by plribeiro3000** [comment]
@mmoll If so can we add this to the gemspec?

**Comment by mmoll** [comment]
yeah, just confirmed I'm getting the same error with 4.x.

**Comment by plribeiro3000** [comment]
@brianjmurrell `fog-libvirt` 0.4.2 released.

Let us know if the problem is fixed. Thanks!

**Comment by brianjmurrell** [comment]
While I didn't go to the effort of upgrading to 0.4.2 I can confirm that upgrading my minitest to 5.x did resolve the issue.

Thanks much!
