### ISSUE TITLE
qemu-guest-agent support

### ISSUE THREAD

**Issue by olifre** [fog/fog-libvirt#55]
`server.xml.erb` is not very configurable right now. 
Adding the lines:
```
    <channel type='unix'>
      <target type='virtio' name='org.qemu.guest_agent.0'/>
    </channel>
```
allows `qemu-guest-agent` connectivity to the VM, which is crucial for `fsfreeze`, `trim` and other commands. 
If this is present on VM creation, e.g. `RHEL 7.5` / `CentOS 7.5` systems install the guest agent with anaconda, and set up the Guest Agent Service automatically.

**Comment by plribeiro3000** [comment]
Hello @olifre . Would you be up to open a PR adding it?

**Comment by olifre** [comment]
Hi @plribeiro3000 , 
the question is whether adding it (without configurability) is fine - this I could do easily. 
But adding a configuration flag requires an API change (I think?) and deeper knowledge of ruby than I currently have... 
Cheers,
Oliver

**Comment by plribeiro3000** [comment]
I do have the knowledge of how fog works and ruby but do not have much about libvirt.

Maybe you can open a PR and we can iterate over it? WDYT?

**Comment by olifre** [comment]
> Maybe you can open a PR and we can iterate over it? WDYT?

Yes, I could do that - I think I will have time in the upcoming weekend ;-). 
For this feature here, a simple "on / off" would probably be sufficient (and my feeling would be that default-on is better).

**Comment by plribeiro3000** [comment]
Coolio!
