### ISSUE TITLE
Change dependency on fog-core to something recent

### ISSUE THREAD

**Issue by johanneskastl** [fog/fog-libvirt#58]
Currently there is a [requirement for fog-core](https://github.com/fog/fog-libvirt/blob/d8ea91406b43f9efbc2e1d267242c6d15fc1fb19/fog-libvirt.gemspec#L28) in an ancient version:

> s.add_dependency("fog-core", "~> 1.27", ">= 1.27.4")

Could this be changed to something more recent? 1.27.4 is from "26 Jan 2015", currently there is 2.1.0...

Kind Regards,
Johannes

**Comment by strzibny** [comment]
Yes, I agree we should move to something more recent.

**Comment by johanneskastl** [comment]
OK, can we merge this then? Or what is missing to get that done?

**Comment by strzibny** [comment]
I checked that fog-core was already relaxed no? So closing this. We can continue discussing fog-xml in the #66.
