### ISSUE TITLE
hugepages support

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-libvirt#6]
Hi,

Would it be possible to optionally enable `hugepages` support for the libvirt driver? This could default to `false`, but having an option to enable it when creating the VM would be great.

When enabled, the `server.xml` template would have:

``` xml
<domain>
  <memoryBacking>
    <hugepages/>
  </memoryBacking>
  ...
</domain>
```

Enabling hugepages support on a Linux system requires a few steps, but I'm guessing documenting them would be outside of fog's scope.

Thank you.

Original issue opened by @eolamey at fog/fog#3342

cc/ @eolamey @geemus

**Comment by eolamey** [comment]
Hi,

I am no longer needing this, should this issue be closed?

**Comment by plribeiro3000** [comment]
Hey @eolamey. Thank you for the feedback but i believe those issues could live here a little longer. Now that we have a small repository it should be easier to add those features. =)

Thanks!
