### ISSUE TITLE
Adding Xen support.

### ISSUE THREAD

**Issue by alvinstarr** [fog/fog-libvirt#72]
fog-libvirt is currently tuned to work with KVM.
With a few changes to the templates  and domain I have been able to use my foreman install to manage my Xen/libvirt based VMs.
What are the chances of altering the templates to support Xen or allowing an alternate source of templates?

**Comment by plribeiro3000** [comment]
@alvinstarr Have you seen [`fog-xenserver`](https://github.com/fog/fog-xenserver)?

I think that we should also support it here since libvirt does support it. Would you open a PR with your changes?

**Comment by alvinstarr** [comment]
xenserver uses a  different configuration scheme than libvirt so fog-xenserver is not that helpful.
I have created a PR and hopefully this will get integrated into Foreman.
