### ISSUE TITLE
 Use libvirt DHCP leases API

### ISSUE THREAD

**Issue by danielshahaf** [fog/fog-libvirt#8]
Fog::Compute::Libvirt::Server#addresses [runs an external shell command](https://github.com/fog/fog-libvirt/blob/e7fa6c2409cf2e740d9e7056ea013f5914a90a13/lib/fog/libvirt/models/compute/server.rb#L311) to determine the IP address of a VM that has a given MAC address. The implementation assumes libvirtd runs on localhost or can be SSHed to; it ignores other cases, such as a TCP transport. Please use [the ruby-libvirt bindings' `dhcp_leases` method](http://libvirt.org/git/?p=ruby-libvirt.git;a=blob;f=ext/libvirt/network.c;h=7c77d730bc9d1c5b4d044873a049ed1f78560b34;hb=HEAD#l287), to also support the case when libvirtd runs on a remote host, using a TCP transport.

The code should be something along these lines:
```
libvirt_conn = @client
libvirt_network = libvirt_conn.lookup_network_by_name('default')
libvirt_network.dhcp_leases('52:54:00:54:74:88')
```

**Comment by danielshahaf** [comment]
A few random bits of background:

- Using that API should also remove the [dependency on arpwatch](https://github.com/fog/fog-libvirt/blob/e7fa6c2409cf2e740d9e7056ea013f5914a90a13/lib/fog/libvirt/models/compute/README.md#ip-addresses-of-guests).

- The `dhcp_leases` method does not appear in the latest ruby-libvirt release, 0.5.2; it's only in git master.

- This was initially reported as https://github.com/pradels/vagrant-libvirt/issues/451

**Comment by domcleal** [comment]
> The dhcp_leases method does not appear in the latest ruby-libvirt release, 0.5.2; it's only in git master.

0.6.0 has been released now with the dhcp_leases API.

**Comment by dcbw** [comment]
PR coming up.  However, even ruby-libvirt 0.6.0 has a bug in the DHCP leases support that causes a crash.  See https://www.redhat.com/archives/libvir-list/2016-January/msg00147.html for the fix.

**Comment by dcbw** [comment]
See https://github.com/fog/fog-libvirt/pull/11
